services:
  backend-api:
    container_name: backend-api
    build:
      context: ./src/backend
    entrypoint: "uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./src/backend:/app
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - ./src/backend/.temp.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis:7.2.3

  worker:
    container_name: worker
    build:
      context: ./src/backend
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - ./src/backend:/app
    depends_on:
      - backend-api
      - redis

volumes:
  pg-data: