services:
  backend-api:
    container_name: backend-api
    build:
      context: ./src/backend
    entrypoint: "uvicorn main:app --host 0.0.0.0 --reload"
    expose:
      - 8000
    volumes:
      - ./src/backend:/app
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:12
    restart: always
    expose:
      - 5432
    env_file:
      - ./src/backend/.temp.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis:7.2.3

  worker:
    container_name: worker
    build:
      context: ./src/backend
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - ./src/backend:/app
    depends_on:
      - backend-api
      - redis

  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
    entrypoint: yarn dev
    expose:
      - 3000
    volumes:
      - ./src/frontend:/app

  nginx:
    container_name: nginx
    image: nginx:1.24
    ports:
      - 80:8080
    volumes:
      - ./src/backend/storage:/app/storage
      - ./src/nginx:/etc/nginx/conf.d
    depends_on:
      - backend-api
      - frontend

volumes:
  pg-data: