"""Init

Revision ID: 5dec3a5a8cca
Revises: 
Create Date: 2023-12-03 12:48:45.926887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dec3a5a8cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_trained', sa.Boolean(), nullable=False),
    sa.Column('model_serialized', sa.LargeBinary(), nullable=True),
    sa.Column('train_dataset_file_path', sa.String(), nullable=True),
    sa.Column('val_dataset_file_path', sa.String(), nullable=True),
    sa.Column('train_loss', sa.LargeBinary(), nullable=True),
    sa.Column('val_loss', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_models')
    # ### end Alembic commands ###
